pay1193/Pay1193/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using Pay1193.Services;
using Pay1193.Entity;
using Pay1193.Models;

namespace Pay1193.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployee _employeeService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public EmployeeController(IEmployee employeeService, IWebHostEnvironment webHostEnvironment)
        {
            _employeeService = employeeService;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            var employee = _employeeService.GetAll().Select(employee => new EmployeeIndexViewModel
            {
                Id = employee.Id,
                EmployeeNo = employee.EmployeeNo,
                FullName = employee.FullName,
                Gender = employee.Gender,
                ImageUrl = employee.ImageUrl,
                DateJoined = employee.DateJoined,
                Designation = employee.Designation,
                Email = employee.Email
            }).ToList();
            return View(employee);
        }

        public IActionResult Detail(int id)
        {
            var employee = _employeeService.GetById(id);
            if(employee == null)
            {
                return NotFound();
            }
            EmployeeDetailsViewModel model = new EmployeeDetailsViewModel()
            {
                Id = employee.Id,
                EmployeeNo = employee.EmployeeNo,
                FullName = employee.FullName,
                Gender = employee.Gender,
                ImageUrl = employee.ImageUrl,
                DoB = employee.DoB,
                Designation = employee.Designation,
                Email = employee.Email,
                NationalInsuranceNo = employee.NationalInsuranceNo,
                PaymentMethod = employee.PaymentMethod,
                StudentLoan = employee.StudentLoan,
                UnionMember = employee.UnionMember,
                Address = employee.Address,
                City = employee.City,
                PostCode = employee.PostCode
            };
            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {
            var model = new EmployeeCreateViewModel();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(EmployeeCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var employee = new Employee
                {
                    Id = model.Id,
                    FirstName = model.FirstName,
                    MiddleName = model.MidleName,
                    LatName = model.LastName,
                    Gender = model.Gender,
                    DoB = model.DOB,
                    DateJoined = model.DateJoined,
                    Designation = model.Designation,
                    NationalInsuranceNo = model.NationalInsuranceNo,
                    StudentLoan = model.StudentLoan,
                    PaymentMethod = model.PaymentMethod,
                    UnionMember= model.UnionMember,
                    Phone = model.Phone,
                    Address = model.Address,
                    City = model.City,
                    PostCode = model.Postcode,
                    Email = model.Email,
                    EmployeeNo = model.EmployeeNo,
                    FullName = model.FullName
                };
                if(model.ImageUrl != null & model.ImageUrl.Length > 0)
                {
                    var uploadDir = @"images/employees";
                    var filename = Path.GetFileNameWithoutExtension(model.ImageUrl.FileName);
                    var extension = Path.GetExtension(model.ImageUrl.FileName);
                    var webrootPath = _webHostEnvironment.WebRootPath;
                    filename = DateTime.UtcNow.ToString("yymmssfff") + filename + extension;
                    var path = Path.Combine(webrootPath,uploadDir, filename);
                    await model.ImageUrl.CopyToAsync(new FileStream(path, FileMode.Create));
                    employee.ImageUrl = "/" + uploadDir + "/" + filename;

                }
                await _employeeService.CreateAsync(employee);
                return RedirectToAction("Index");
            }
            return View(); 
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var employee = _employeeService.GetById(id);
            if(employee == null)
            {
                return NotFound();
            }
            var model = new EmployeeEditViewModel()
            {
                Id = employee.Id,
                FirstName = employee.FirstName,
                LastName = employee.LatName,
                MidleName = employee.MiddleName,
                EmployeeNo = employee.EmployeeNo,
                Gender = employee.Gender,
                Email = employee.Email,
                DOB = employee.DoB,
                DateJoined = employee.DateJoined,
                Designation = employee.Designation,
                NationalInsuranceNo = employee.NationalInsuranceNo,
                PaymentMethod = employee.PaymentMethod,
                StudentLoan = employee.StudentLoan,
                UnionMember = employee.UnionMember,
                Address = employee.Address,
                City = employee.City,
                Postcode = employee.PostCode
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EmployeeEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var employee = new Employee
                {
                    Id = model.Id,
                    FirstName = model.FirstName,
                    MiddleName = model.MidleName,
                    LatName = model.LastName,
                    Gender = model.Gender,
                    DoB = model.DOB,
                    DateJoined = model.DateJoined,
                    Designation = model.Designation,
                    NationalInsuranceNo = model.NationalInsuranceNo,
                    StudentLoan = model.StudentLoan,
                    PaymentMethod = model.PaymentMethod,
                    UnionMember = model.UnionMember,
                    Phone = model.Phone,
                    Address = model.Address,
                    City = model.City,
                    PostCode = model.Postcode,
                    Email = model.Email,
                    EmployeeNo = model.EmployeeNo,
                    FullName = model.FullName
                };
                if (model.ImageUrl != null & model.ImageUrl.Length > 0)
                {
                    var uploadDir = @"images/employees";
                    var filename = Path.GetFileNameWithoutExtension(model.ImageUrl.FileName);
                    var extension = Path.GetExtension(model.ImageUrl.FileName);
                    var webrootPath = _webHostEnvironment.WebRootPath;
                    filename = DateTime.UtcNow.ToString("yymmssfff") + filename + extension;
                    var path = Path.Combine(webrootPath, uploadDir, filename);
                    await model.ImageUrl.CopyToAsync(new FileStream(path, FileMode.Create));
                    employee.ImageUrl = "/" + uploadDir + "/" + filename;

                }
                await _employeeService.UpdateAsync(employee);
                return RedirectToAction("Index");
            }
            return View();
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var employee = _employeeService.GetById(id);
            if(employee == null)
            {
                return NotFound();
            }
            var model = new EmployeeDeleteViewModel
            {
                Id = employee.Id,
                FullName = employee.FullName
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Delete(EmployeeDeleteViewModel model)
        {
            await _employeeService.Delete(model.Id);
            return RedirectToAction("Index");
        }
    }
}

pay1193/Pay1193/Controllers/PaymentRecordsController.cs
using Microsoft.AspNetCore.Mvc;
//using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.VisualBasic;
using Pay1193.Entity;
using Pay1193.Models;
using Pay1193.Services;
using Pay1193.Services.Implement;
using System.Text;

namespace Pay1193.Controllers
{
    public class PaymentRecordsController : Controller
    {
        private readonly IPayService _paymentService;
        private readonly IEmployee _employeeService;
        private readonly INationalInsuranceService _nationalInsuranceService;
        private readonly ITaxService _taxService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private decimal overtimehours;
        private decimal overtimeearnings;
        private decimal contractualearnings;
        private decimal totalearnings;
        private decimal taxamount;
        private decimal nic;
        private decimal slc;
        private decimal unionfee;

        public PaymentRecordsController(IPayService paymentService, IEmployee employeeService, INationalInsuranceService nationalInsuranceService, ITaxService taxService, IWebHostEnvironment webHostEnvironment)
        {
            _paymentService = paymentService;
            _employeeService = employeeService;
            _nationalInsuranceService = nationalInsuranceService;
            _taxService = taxService;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            var paymentrecord = _paymentService.GetAll().Select(paymentrecord => new PaymentRecordsIndexViewModel
            {
                Id = paymentrecord.Id,
                EmployeeId = paymentrecord.EmployeeId,
                EmployeeFullName = _employeeService.GetNameById(paymentrecord.EmployeeId),
                Employee = paymentrecord.Employee,
                DatePay = paymentrecord.DatePay,
                MonthPay = paymentrecord.MonthPay,
                TaxYearId = paymentrecord.TaxYearId,
                TaxCode = paymentrecord.TaxCode,
                TotalEarnings = paymentrecord.TotalEarnings,
                NetPayment = paymentrecord.NetPayment

            }).ToList();
            return View(paymentrecord);
        }

        public IActionResult Detail(int id)
        {
            var paymentrecord = _paymentService.GetById(id);
            if (paymentrecord == null)
            {
                return NotFound();
            }
            PaymentRecordsDetailsViewModel model = new PaymentRecordsDetailsViewModel()
            {
                Id = paymentrecord.Id,
                EmployeeId = paymentrecord.EmployeeId,
                DatePay = paymentrecord.DatePay,
                MonthPay = paymentrecord.MonthPay,
                TaxYearId = paymentrecord.TaxYearId,
                TaxCode = paymentrecord.TaxCode,
                HourlyRate = paymentrecord.HourlyRate,
                HourWorked = paymentrecord.HourWorked,
                ContractualHours = paymentrecord.ContractualHours,
                OvertimeHours = _paymentService.OverTimeHours(paymentrecord.HourWorked, paymentrecord.ContractualHours),
                OvertimeRate = _paymentService.OvertimeRate(paymentrecord.HourlyRate),
                ContractualEarnings = paymentrecord.ContractualEarnings,
                OvertimeEarnings = paymentrecord.OvertimeEarnings,
                NiC = paymentrecord.NiC,
                Tax = paymentrecord.Tax,
                UnionFee = paymentrecord.UnionFee,
                SLC = paymentrecord.SLC,
                TotalEarnings = paymentrecord.TotalEarnings,
                NetPayment = paymentrecord.NetPayment
            };
            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.employees = _employeeService.FillSelectBoxWithEmployees();
            ViewBag.taxYears = _paymentService.GetAllTaxYear();
            var model = new PaymentRecordsCreateViewModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PaymentRecordsCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var paymentrecord = new PaymentRecord
                {
                    Id = model.Id,
                    EmployeeId = model.EmployeeId,
                    DatePay = model.DatePay,
                    MonthPay = model.MonthPay,
                    TaxYearId = model.TaxYearId,
                    TaxCode = model.TaxCode,
                    HourlyRate = model.HourlyRate,
                    HourWorked = model.HourWorked,
                    ContractualHours = model.ContractualHours,
                    OvertimeHours = overtimehours = _paymentService.OverTimeHours(model.HourWorked, model.ContractualHours),
                    ContractualEarnings = contractualearnings = _paymentService.ContractualEarning(model.ContractualHours, model.HourWorked, model.HourlyRate),
                    OvertimeEarnings = overtimeearnings = _paymentService.OvertimeEarnings(_paymentService.OvertimeRate(model.HourlyRate), _paymentService.OverTimeHours(model.HourWorked, model.ContractualHours)),
                    TotalEarnings = totalearnings = _paymentService.TotalEarnings(overtimeearnings, contractualearnings),
                    NiC = nic = _nationalInsuranceService.NIContribution(totalearnings),
                    Tax = taxamount = _taxService.TaxAmount(totalearnings),
                    UnionFee = unionfee = _employeeService.UnionFee(model.EmployeeId),
                    SLC = _employeeService.StudentLoanRepaymentAmount(model.EmployeeId, totalearnings),
                    NetPayment = _paymentService.NetPay(totalearnings, _paymentService.TotalDeduction(taxamount,nic,slc,unionfee)),
                };
                await _paymentService.CreateAsync(paymentrecord);
                return RedirectToAction("Index");
            }
            ViewBag.employees = _employeeService.FillSelectBoxWithEmployees();
            ViewBag.taxYears = _paymentService.GetAllTaxYear();
            return View(model);
        }
    }
}

pay1193/Pay1193/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pay1193</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Pay1193.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css" />
</head>
<body>
    <div class="container-scroller">
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-grow">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <a class="navbar-brand brand-logo"><img src="~/images/Emp.gif" alt="logo" /> </a>
            </div>
        </nav>
        <div class="container-fluid page-body-wrapper">
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav list-unstyled ps-0">
                    <li class="mb-1">
                        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#employee" aria-expanded="false">
                            <i class="fas fa-users fa-lg text-secondary" style="margin-right:auto.7em"></i>
                            <span class="menu-title">Employee</span>
                            <i class="menu-arrow text-secondary"></i>
                        </button>
                        <div class="collapse" id="employee">
                            <ul class="btn-toggle-nav list-unstyled flex-column sub-menu">
                                <li class="nav-item"><a asp-controller="Employee" asp-action="Create" class="nav-link">New Employee</a></li>
                                <li class="nav-item"><a asp-controller="Employee" asp-action="Index" class="nav-link">All Employess</a></li>
                            </ul>
                        </div>
                    </li>
                    <li class="mb-1">
                        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" data-bs-toggle="collapse" data-bs-target="#payment" aria-expanded="false">
                            <i class="fas fa-pound-sign fa-lg text-primary" style="margin-right:auto.7em"></i>
                            <span class="menu-title">PayMent</span>
                            <i class="menu-arrow text-secondary"></i>
                        </button>
                        <div class="collapse" id="payment">
                            <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                                <li class="nav-item"><a asp-controller="PaymentRecords" asp-action="Create" class="nav-link">New Pay</a></li>
                                <li class="nav-item"><a asp-controller="PaymentRecords" asp-action="Index" class="nav-link">Pay Method</a></li>
                            </ul>
                        </div>
                    </li>
                   
                   
                </ul>
            </nav>
            <div class="main-panel">
                <div class="content-wrapper">
                    @RenderBody()
                </div>
                <footer>
                    <p>&copy; @DateTime.UtcNow.Year - Pay1193</p>
                </footer>
            </div>
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>